/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica7smm;

import java.awt.GraphicsEnvironment;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author joset
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna() {
        initComponents();
        this.setSize(600,400);
        
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fuentesSistema = ge.getAvailableFontFamilyNames();
        ListaFuentes.setModel(new DefaultComboBoxModel(fuentesSistema));
    }

    public Lienzo2D getLienzo(){
        return Lienzo2D;
    }
  
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSur = new javax.swing.JPanel();
        ListaFuentes = new javax.swing.JComboBox<>();
        VentanaClipActiva = new javax.swing.JCheckBox();
        Lienzo2D = new practica7smm.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        ListaFuentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaFuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaFuentesActionPerformed(evt);
            }
        });
        PanelSur.add(ListaFuentes);

        VentanaClipActiva.setText("VentanaClipActiva");
        VentanaClipActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaClipActivaActionPerformed(evt);
            }
        });
        PanelSur.add(VentanaClipActiva);

        getContentPane().add(PanelSur, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(Lienzo2D, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaFuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaFuentesActionPerformed
        Lienzo2D.setFuente((String)ListaFuentes.getSelectedItem());
        Lienzo2D.repaint();
    }//GEN-LAST:event_ListaFuentesActionPerformed

    private void VentanaClipActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaClipActivaActionPerformed
        this.Lienzo2D.setVentanaClipActiva(VentanaClipActiva.isSelected());
        Lienzo2D.repaint();
    }//GEN-LAST:event_VentanaClipActivaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private practica7smm.Lienzo2D Lienzo2D;
    private javax.swing.JComboBox<String> ListaFuentes;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JCheckBox VentanaClipActiva;
    // End of variables declaration//GEN-END:variables
}
