/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package practica7smm;

import java.awt.GraphicsEnvironment;
import java.awt.geom.Point2D;
import javax.swing.DefaultComboBoxModel;
import sm.JTLV.iu.Lienzo2D;

/**
 *
 * @author joset
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna() {
        initComponents();
        this.setSize(600,400);
        
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fuentesSistema = ge.getAvailableFontFamilyNames();
        ListaFuentes.setModel(new DefaultComboBoxModel(fuentesSistema));
    }

    public Lienzo2D getLienzo(){
        return Lienzo2D;
    }

    public String getCoordenadas(){
        return Coordenadas.getText();
    }
  
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSur = new javax.swing.JPanel();
        ListaFuentes = new javax.swing.JComboBox<>();
        VentanaClipActiva = new javax.swing.JCheckBox();
        Coordenadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lienzo2D = new sm.JTLV.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        PanelSur.setLayout(new java.awt.BorderLayout());

        ListaFuentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ListaFuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaFuentesActionPerformed(evt);
            }
        });
        PanelSur.add(ListaFuentes, java.awt.BorderLayout.LINE_START);

        VentanaClipActiva.setText("VentanaClipActiva");
        VentanaClipActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentanaClipActivaActionPerformed(evt);
            }
        });
        PanelSur.add(VentanaClipActiva, java.awt.BorderLayout.CENTER);

        Coordenadas.setText("Coordenadas");
        PanelSur.add(Coordenadas, java.awt.BorderLayout.LINE_END);

        getContentPane().add(PanelSur, java.awt.BorderLayout.PAGE_END);

        Lienzo2D.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Lienzo2DMouseMoved(evt);
            }
        });
        jScrollPane1.setViewportView(Lienzo2D);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaFuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaFuentesActionPerformed
        Lienzo2D.setFuente((String)ListaFuentes.getSelectedItem());
        Lienzo2D.repaint();
    }//GEN-LAST:event_ListaFuentesActionPerformed

    private void VentanaClipActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentanaClipActivaActionPerformed
        this.Lienzo2D.setVentanaClipActiva(VentanaClipActiva.isSelected());
        Lienzo2D.repaint();
    }//GEN-LAST:event_VentanaClipActivaActionPerformed

    private void Lienzo2DMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lienzo2DMouseMoved
        if(Lienzo2D != null 
                && Lienzo2D.getCoordenada() != null){
            double mx = Lienzo2D.getCoordenada().getX();
            double my = Lienzo2D.getCoordenada().getY();
            Coordenadas.setText( mx + "x" + my );
        }
    }//GEN-LAST:event_Lienzo2DMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Coordenadas;
    private sm.JTLV.iu.Lienzo2D Lienzo2D;
    private javax.swing.JComboBox<String> ListaFuentes;
    private javax.swing.JPanel PanelSur;
    private javax.swing.JCheckBox VentanaClipActiva;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
