/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practica5smm;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.*;
import java.util.*;
import practica5smm.Linea2D;

/**
 *
 * @author joset
 */
public class Lienzo2D extends javax.swing.JPanel {

    /**
     * Creates new form Lienzo2D
     */
    public Lienzo2D() {
        initComponents();
        
    }
    private List<Shape> vShape = new ArrayList();
    private Color color = Color.black;
    private Forma form = Forma.LINEA;
    Shape forma = new Linea2D.Double(0,0,0,0);
    private boolean relleno, mover = false;

    public boolean isMover() {
        return mover;
    }

    public void setMover(boolean mover) {
        this.mover = mover;
    }
    private Point2D puntoInicial = new Point(0,0);
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d = (Graphics2D)g;
        g2d.setPaint(color);
        for(Shape s:vShape){
            if (relleno)
                g2d.fill(forma);
            g2d.draw(s);
        }
    }
    
    public void setColor(Color color){
        this.color = color;
    }
    public Color getColor(){
        return color;
    }
    
    public void setForma(Forma form){
        this.form = form;
    }
    
    public Forma getForma(){
        return form;
    }

    public enum Forma{
        LINEA, RECTANGULO, ELIPSE
    }
    
    public void setRelleno(boolean relleno){
        this.relleno = relleno;
    }
    
    public boolean getRelleno(){
        return relleno;
    }
    
    public void nuevo(){
        setForma(Forma.LINEA);
        setRelleno(false);
        setColor(Color.BLACK);
        puntoInicial.setLocation(0, 0);
        forma = new Line2D.Double(0,0,0,0);
        vShape.add(forma);
        this.repaint();
    }
    
    private Shape getFiguraSeleccionada(Point2D p){
        for(Shape s:vShape)
            if(s.contains(p))
                return s;
        return null;
    }
    
/*    public void setLocation(Point2D pos){
        double dx = pos.getX() - this.getX();
        double dy = pos.getY() - this.getY();
        Point2D newp2 = new Point2D.Double(this.getX()+dx,this.getY()+dy);
        this.setLine(pos,newp2);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if(mover)
            forma = getFiguraSeleccionada(evt.getPoint());
        else {
            switch(form){
                case LINEA:
                    forma = new Linea2D(evt.getPoint(), evt.getPoint());
                    break;
                case RECTANGULO:
                    forma = new Rectangle2D.Float(evt.getPoint().x,evt.getPoint().y,0,0);
                    break;
                case ELIPSE:
                    forma = new Ellipse2D.Float(evt.getPoint().x,evt.getPoint().y,0,0);
                    break;
            }
            puntoInicial = evt.getPoint();
            vShape.add(forma);
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        if(mover){
            //Código para el caso del rectángulo
            if (forma!=null && forma instanceof Rectangle2D){
                double NuevoX = this.getMousePosition().getX() - puntoInicial.getX();
                double NuevoY = this.getMousePosition().getY() - puntoInicial.getY();

                ((Rectangle2D)forma).setFrame(
                        NuevoX, 
                        NuevoY, 
                        ((Rectangle2D)forma).getWidth(), 
                        ((Rectangle2D)forma).getHeight());
            }
            else if (forma!=null && forma instanceof Ellipse2D)
                ((Ellipse2D)forma).setFrame(
                        evt.getPoint().getX(), 
                        evt.getPoint().getY(), 
                        ((Ellipse2D)forma).getWidth(), 
                        ((Ellipse2D)forma).getHeight());
            else if (forma!=null && forma instanceof Linea2D)
                ((Linea2D)forma).setLocation(evt.getPoint());
        }
        else {
            switch(form){
                case LINEA:
                    ((Linea2D)forma).setLine(((Linea2D)forma).getP1(), evt.getPoint());
                    break;
                case RECTANGULO:
                    ((Rectangle2D)forma).setFrameFromDiagonal(puntoInicial, evt.getPoint());
                    break;
                case ELIPSE:
                    ((Ellipse2D)forma).setFrameFromDiagonal(puntoInicial, evt.getPoint());
                    break;
            }
        }
        this.repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
