/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica4smm;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import practica4smm.Lienzo2D.Forma;

/**
 *
 * @author joset
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        //this.setSize(800,600);
        this.setTitle("Paint Basico");
    }
    
    /*@Override
    public void paint(Graphics g){
        super.paint(g);
        g.fillOval(this.getMousePosition().x, this.getMousePosition().y, 30, 30);
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Linea = new javax.swing.JToggleButton();
        rectangulo = new javax.swing.JToggleButton();
        Elipse = new javax.swing.JToggleButton();
        Lienzo2D = new practica4smm.Lienzo2D();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ColorNegro = new javax.swing.JButton();
        ColorRojo = new javax.swing.JButton();
        ColorAzul = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        ColorBlanco = new javax.swing.JButton();
        ColorAmarillo = new javax.swing.JButton();
        ColorVerde = new javax.swing.JButton();
        Relleno = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        BarraDeEstado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Nuevo = new javax.swing.JMenuItem();
        Abrir = new javax.swing.JMenuItem();
        Guardar = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(214, 217, 223));

        jToolBar1.setBackground(new java.awt.Color(214, 217, 223));
        jToolBar1.setRollover(true);

        Linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        Linea.setFocusable(false);
        Linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Linea.addActionListener(formListener);
        jToolBar1.add(Linea);

        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rectangulo.png"))); // NOI18N
        rectangulo.setFocusable(false);
        rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectangulo.addActionListener(formListener);
        jToolBar1.add(rectangulo);

        Elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipse.png"))); // NOI18N
        Elipse.setFocusable(false);
        Elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Elipse.addActionListener(formListener);
        jToolBar1.add(Elipse);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        Lienzo2D.setBackground(new java.awt.Color(255, 255, 255));
        Lienzo2D.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout Lienzo2DLayout = new javax.swing.GroupLayout(Lienzo2D);
        Lienzo2D.setLayout(Lienzo2DLayout);
        Lienzo2DLayout.setHorizontalGroup(
            Lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        Lienzo2DLayout.setVerticalGroup(
            Lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        getContentPane().add(Lienzo2D, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(214, 217, 223));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(214, 217, 223));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(214, 217, 223));

        ColorNegro.setBackground(new java.awt.Color(0, 0, 0));
        ColorNegro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColorNegro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ColorNegro.setMaximumSize(new java.awt.Dimension(23, 20));
        ColorNegro.setMinimumSize(new java.awt.Dimension(23, 20));
        ColorNegro.setPreferredSize(new java.awt.Dimension(23, 20));
        ColorNegro.addActionListener(formListener);
        jPanel5.add(ColorNegro);

        ColorRojo.setBackground(new java.awt.Color(255, 0, 0));
        ColorRojo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColorRojo.setMaximumSize(new java.awt.Dimension(23, 20));
        ColorRojo.setMinimumSize(new java.awt.Dimension(23, 20));
        ColorRojo.setPreferredSize(new java.awt.Dimension(23, 20));
        ColorRojo.addActionListener(formListener);
        jPanel5.add(ColorRojo);

        ColorAzul.setBackground(new java.awt.Color(0, 0, 255));
        ColorAzul.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColorAzul.setMaximumSize(new java.awt.Dimension(23, 20));
        ColorAzul.setMinimumSize(new java.awt.Dimension(23, 20));
        ColorAzul.setName(""); // NOI18N
        ColorAzul.setPreferredSize(new java.awt.Dimension(23, 20));
        ColorAzul.addActionListener(formListener);
        jPanel5.add(ColorAzul);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setBackground(new java.awt.Color(214, 217, 223));

        ColorBlanco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColorBlanco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ColorBlanco.setMaximumSize(new java.awt.Dimension(23, 20));
        ColorBlanco.setMinimumSize(new java.awt.Dimension(23, 20));
        ColorBlanco.setPreferredSize(new java.awt.Dimension(23, 20));
        ColorBlanco.addActionListener(formListener);
        jPanel6.add(ColorBlanco);

        ColorAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        ColorAmarillo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColorAmarillo.setMaximumSize(new java.awt.Dimension(23, 20));
        ColorAmarillo.setMinimumSize(new java.awt.Dimension(23, 20));
        ColorAmarillo.setName(""); // NOI18N
        ColorAmarillo.setPreferredSize(new java.awt.Dimension(23, 20));
        ColorAmarillo.addActionListener(formListener);
        jPanel6.add(ColorAmarillo);

        ColorVerde.setBackground(new java.awt.Color(0, 255, 0));
        ColorVerde.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColorVerde.setMaximumSize(new java.awt.Dimension(23, 20));
        ColorVerde.setMinimumSize(new java.awt.Dimension(23, 20));
        ColorVerde.setPreferredSize(new java.awt.Dimension(23, 20));
        ColorVerde.addActionListener(formListener);
        jPanel6.add(ColorVerde);

        jPanel4.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        Relleno.setBackground(new java.awt.Color(214, 217, 223));
        Relleno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Relleno.setText("Relleno");
        Relleno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Relleno.addActionListener(formListener);
        jPanel2.add(Relleno, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(214, 217, 223));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        BarraDeEstado.setBackground(new java.awt.Color(214, 214, 214));
        BarraDeEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BarraDeEstado.setText("Barra de estado");
        BarraDeEstado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel3.add(BarraDeEstado, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jMenuBar1.setBackground(new java.awt.Color(214, 217, 223));

        Archivo.setText("Archivo");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(formListener);
        Archivo.add(Nuevo);

        Abrir.setText("Abrir");
        Abrir.addActionListener(formListener);
        Archivo.add(Abrir);

        Guardar.setText("Guardar");
        Guardar.addActionListener(formListener);
        Archivo.add(Guardar);

        jMenuBar1.add(Archivo);

        setJMenuBar(jMenuBar1);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == Linea) {
                VentanaPrincipal.this.LineaActionPerformed(evt);
            }
            else if (evt.getSource() == rectangulo) {
                VentanaPrincipal.this.rectanguloActionPerformed(evt);
            }
            else if (evt.getSource() == Elipse) {
                VentanaPrincipal.this.ElipseActionPerformed(evt);
            }
            else if (evt.getSource() == ColorNegro) {
                VentanaPrincipal.this.ColorNegroActionPerformed(evt);
            }
            else if (evt.getSource() == ColorRojo) {
                VentanaPrincipal.this.ColorRojoActionPerformed(evt);
            }
            else if (evt.getSource() == ColorAzul) {
                VentanaPrincipal.this.ColorAzulActionPerformed(evt);
            }
            else if (evt.getSource() == ColorBlanco) {
                VentanaPrincipal.this.ColorBlancoActionPerformed(evt);
            }
            else if (evt.getSource() == ColorAmarillo) {
                VentanaPrincipal.this.ColorAmarilloActionPerformed(evt);
            }
            else if (evt.getSource() == ColorVerde) {
                VentanaPrincipal.this.ColorVerdeActionPerformed(evt);
            }
            else if (evt.getSource() == Relleno) {
                VentanaPrincipal.this.RellenoActionPerformed(evt);
            }
            else if (evt.getSource() == Nuevo) {
                VentanaPrincipal.this.NuevoActionPerformed(evt);
            }
            else if (evt.getSource() == Abrir) {
                VentanaPrincipal.this.AbrirActionPerformed(evt);
            }
            else if (evt.getSource() == Guardar) {
                VentanaPrincipal.this.GuardarActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaActionPerformed
        this.Lienzo2D.setForma(Forma.LINEA);
        BarraDeEstado.setText("Linea");
        rectangulo.setSelected(false);
        Elipse.setSelected(false);
    }//GEN-LAST:event_LineaActionPerformed

    private void RellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoActionPerformed
        this.Lienzo2D.setRelleno(Relleno.isSelected());
    }//GEN-LAST:event_RellenoActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        this.Lienzo2D.nuevo();
    }//GEN-LAST:event_NuevoActionPerformed

    private void ColorNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorNegroActionPerformed
        this.Lienzo2D.setColor(Color.black);
    }//GEN-LAST:event_ColorNegroActionPerformed

    private void ColorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorRojoActionPerformed
        this.Lienzo2D.setColor(Color.red);
    }//GEN-LAST:event_ColorRojoActionPerformed

    private void ColorAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorAzulActionPerformed
        this.Lienzo2D.setColor(Color.blue);
    }//GEN-LAST:event_ColorAzulActionPerformed

    private void ColorBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorBlancoActionPerformed
        this.Lienzo2D.setColor(Color.white);
    }//GEN-LAST:event_ColorBlancoActionPerformed

    private void ColorAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorAmarilloActionPerformed
        this.Lienzo2D.setColor(Color.yellow);
    }//GEN-LAST:event_ColorAmarilloActionPerformed

    private void ColorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorVerdeActionPerformed
        this.Lienzo2D.setColor(Color.green);
    }//GEN-LAST:event_ColorVerdeActionPerformed

    private void rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloActionPerformed
        this.Lienzo2D.setForma(Forma.RECTANGULO);
        BarraDeEstado.setText("Rectangulo");
        Linea.setSelected(false);
        Elipse.setSelected(false);
    }//GEN-LAST:event_rectanguloActionPerformed

    private void ElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElipseActionPerformed
        this.Lienzo2D.setForma(Forma.ELIPSE);
        BarraDeEstado.setText("Elipse");
        rectangulo.setSelected(false);
        Linea.setSelected(false);
    }//GEN-LAST:event_ElipseActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abrir;
    private javax.swing.JMenu Archivo;
    private javax.swing.JLabel BarraDeEstado;
    private javax.swing.JButton ColorAmarillo;
    private javax.swing.JButton ColorAzul;
    private javax.swing.JButton ColorBlanco;
    private javax.swing.JButton ColorNegro;
    private javax.swing.JButton ColorRojo;
    private javax.swing.JButton ColorVerde;
    private javax.swing.JToggleButton Elipse;
    private javax.swing.JMenuItem Guardar;
    private practica4smm.Lienzo2D Lienzo2D;
    private javax.swing.JToggleButton Linea;
    private javax.swing.JMenuItem Nuevo;
    private javax.swing.JCheckBox Relleno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton rectangulo;
    // End of variables declaration//GEN-END:variables


}
