
all:
	@g++ -oBurbuja.bin Burbuja.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo iterativo con ./Burbuja.bin salida.txt 12345 1000 2000 3000
	@g++ -oMergeSort.bin mergesort.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./MergeSort.bin salida.txt 12345 1000 2000 3000
	@g++ -oej1fb.bin ej1fb.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo basico con ./ej1fb.bin salida_ej1fb.txt
	@g++ -oalu.bin alu.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo DyV con ./alu.bin salida_alu.txt
	@g++ -oej3fb.bin ej3fb.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo basico con ./ej3fb.bin salida_ej3fb.txt
